import PDFDocument from 'pdfkit';

/**
 * Generate a professional bulk appointments PDF report stream
 */
export const buildAppointmentsPdfStream = (appointments = [], filters = {}, adminUser = {}) => {
  const doc = new PDFDocument({
    margin: 40,
    size: 'A4',
    bufferPages: true,
    info: {
      Title: 'HealPoint Clinical Appointments Report',
      Author: 'HealPoint Healthcare Management System',
      Subject: 'Appointment Administration Report'
    }
  });

  // Colors
  const brandNavy = '#111C2F';
  const brandTeal = '#087F72';
  const textDark = '#172033';
  const textMuted = '#64748B';
  const borderLight = '#E2E8F0';
  const zebraBg = '#F8FAFC';

  // 1. Header Banner
  doc.rect(40, 40, 515, 60).fill(brandNavy);
  
  // Teal accent line
  doc.rect(40, 100, 515, 4).fill(brandTeal);

  doc.fillColor('#FFFFFF')
     .fontSize(16)
     .font('Helvetica-Bold')
     .text('HEALPOINT HEALTHCARE SYSTEMS', 55, 52);

  doc.fontSize(10)
     .font('Helvetica')
     .fillColor('#94A3B8')
     .text('Clinical Appointment Administration & Governance Report', 55, 74);

  doc.fontSize(8)
     .fillColor('#A7F3D0')
     .text(`Generated on: ${new Date().toLocaleString()}`, 380, 56, { align: 'right', width: 160 });

  doc.text(`Generated by: ${adminUser.email || 'admin@healpoint.com'}`, 380, 70, { align: 'right', width: 160 });

  // 2. Filter Summary Box
  let y = 120;
  doc.rect(40, y, 515, 45).fillAndStroke('#F1F5F9', borderLight);

  doc.fillColor(textDark)
     .fontSize(9)
     .font('Helvetica-Bold')
     .text('APPLIED REPORT FILTERS & PARAMETERS', 50, y + 8);

  const statusLabel = filters.status || 'ALL STATUSES';
  const specialtyLabel = filters.specialty || 'ALL SPECIALTIES';
  const searchLabel = filters.search ? `"${filters.search}"` : 'NONE';
  const dateRangeLabel = (filters.startDate || filters.endDate) 
    ? `${filters.startDate || 'Start'} to ${filters.endDate || 'Present'}`
    : 'ALL RECORDED DATES';

  doc.fontSize(8)
     .font('Helvetica')
     .fillColor(textMuted)
     .text(`Status Filter: `, 50, y + 24, { continued: true })
     .font('Helvetica-Bold').fillColor(textDark).text(`${statusLabel}   |   `, { continued: true })
     .font('Helvetica').fillColor(textMuted).text(`Specialty: `, { continued: true })
     .font('Helvetica-Bold').fillColor(textDark).text(`${specialtyLabel}   |   `, { continued: true })
     .font('Helvetica').fillColor(textMuted).text(`Date Range: `, { continued: true })
     .font('Helvetica-Bold').fillColor(textDark).text(`${dateRangeLabel}`);

  doc.font('Helvetica')
     .fillColor(textMuted)
     .text(`Search Term: `, 50, y + 34, { continued: true })
     .font('Helvetica-Bold').fillColor(textDark).text(`${searchLabel}   |   `, { continued: true })
     .font('Helvetica').fillColor(textMuted).text(`Matching Records: `, { continued: true })
     .font('Helvetica-Bold').fillColor(brandTeal).text(`${appointments.length} Bookings`);

  // 3. Table Header
  y = 180;
  const colX = { id: 45, patient: 85, doctor: 195, date: 310, type: 395, status: 455, fee: 510 };
  
  const drawTableHeader = (posY) => {
    doc.rect(40, posY, 515, 20).fill(brandTeal);
    doc.fillColor('#FFFFFF')
       .fontSize(8)
       .font('Helvetica-Bold')
       .text('ID', colX.id, posY + 6)
       .text('PATIENT', colX.patient, posY + 6)
       .text('DOCTOR & SPECIALTY', colX.doctor, posY + 6)
       .text('DATE & TIME', colX.date, posY + 6)
       .text('MODE', colX.type, posY + 6)
       .text('STATUS', colX.status, posY + 6)
       .text('FEE', colX.fee, posY + 6);
  };

  drawTableHeader(y);
  y += 20;

  if (appointments.length === 0) {
    doc.rect(40, y, 515, 40).fillAndStroke('#FFFFFF', borderLight);
    doc.fillColor(textMuted)
       .fontSize(9)
       .font('Helvetica')
       .text('No appointments found matching the specified filter criteria.', 50, y + 15, { align: 'center', width: 495 });
    y += 40;
  } else {
    // 4. Table Rows
    appointments.forEach((apt, idx) => {
      // Check page overflow
      if (y > 740) {
        doc.addPage();
        y = 45;
        drawTableHeader(y);
        y += 20;
      }

      const isEven = idx % 2 === 0;
      doc.rect(40, y, 515, 24).fillAndStroke(isEven ? zebraBg : '#FFFFFF', borderLight);

      doc.fillColor(textDark)
         .fontSize(8)
         .font('Helvetica-Bold')
         .text(`#${apt.appointment_id}`, colX.id, y + 7);

      doc.font('Helvetica-Bold')
         .text(apt.patient_name || 'Patient', colX.patient, y + 4, { width: 105, height: 10, ellipsis: true })
         .font('Helvetica')
         .fillColor(textMuted)
         .fontSize(7)
         .text(apt.patient_email || '', colX.patient, y + 14, { width: 105, height: 9, ellipsis: true });

      doc.fillColor(textDark)
         .fontSize(8)
         .font('Helvetica-Bold')
         .text(apt.doctor_name || 'Dr. Specialist', colX.doctor, y + 4, { width: 110, height: 10, ellipsis: true })
         .font('Helvetica')
         .fillColor(brandTeal)
         .fontSize(7)
         .text(apt.specialization || 'Medicine', colX.doctor, y + 14, { width: 110, height: 9, ellipsis: true });

      const dateStr = apt.appointment_datetime ? new Date(apt.appointment_datetime).toLocaleDateString() : '';
      const timeStr = apt.appointment_datetime ? new Date(apt.appointment_datetime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '';
      doc.fillColor(textDark)
         .fontSize(8)
         .font('Helvetica')
         .text(dateStr, colX.date, y + 4)
         .fillColor(textMuted)
         .fontSize(7)
         .text(timeStr, colX.date, y + 14);

      doc.fillColor(apt.appointment_type === 'VIDEO' ? '#2563EB' : textDark)
         .fontSize(7.5)
         .font('Helvetica')
         .text(apt.appointment_type === 'VIDEO' ? 'Telemedicine' : 'In-Person', colX.type, y + 7);

      const statusColor = apt.status === 'COMPLETED' ? '#059669' : (apt.status === 'CANCELLED' ? '#DC2626' : '#D97706');
      doc.fillColor(statusColor)
         .fontSize(7.5)
         .font('Helvetica-Bold')
         .text(apt.status || 'SCHEDULED', colX.status, y + 7);

      doc.fillColor(textDark)
         .fontSize(8)
         .font('Helvetica-Bold')
         .text(`$${apt.payment_amount || 65.00}`, colX.fee, y + 7);

      y += 24;
    });
  }

  // 5. Total Volume Summary
  const totalRev = appointments
    .filter(a => a.status === 'COMPLETED' || a.payment_status === 'COMPLETED')
    .reduce((sum, a) => sum + (Number(a.payment_amount) || 65), 0);

  if (y > 720) {
    doc.addPage();
    y = 45;
  }

  y += 10;
  doc.rect(40, y, 515, 30).fill(brandNavy);
  doc.fillColor('#FFFFFF')
     .fontSize(9)
     .font('Helvetica-Bold')
     .text(`REPORT SUMMARY: ${appointments.length} Total Appointments Filtered`, 55, y + 10)
     .text(`Completed Consultation Volume: $${totalRev.toFixed(2)}`, 320, y + 10, { align: 'right', width: 220 });

  // 6. Page Numbers in Footer
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(7.5)
       .fillColor(textMuted)
       .font('Helvetica')
       .text(
         `HealPoint Clinical Health Systems • Confidential Administration Document • Page ${i + 1} of ${range.count}`,
         40,
         790,
         { align: 'center', width: 515 }
       );
  }

  return doc;
};

/**
 * Generate a dedicated single appointment summary receipt PDF
 */
export const buildSingleAppointmentPdfStream = (apt, adminUser = {}) => {
  const doc = new PDFDocument({
    margin: 40,
    size: 'A4',
    info: {
      Title: `HealPoint Appointment Summary #${apt.appointment_id}`,
      Author: 'HealPoint Healthcare Management System'
    }
  });

  const brandNavy = '#111C2F';
  const brandTeal = '#087F72';
  const textDark = '#172033';
  const textMuted = '#64748B';
  const borderLight = '#E2E8F0';

  // 1. Header
  doc.rect(40, 40, 515, 65).fill(brandNavy);
  doc.rect(40, 105, 515, 4).fill(brandTeal);

  doc.fillColor('#FFFFFF')
     .fontSize(16)
     .font('Helvetica-Bold')
     .text('HEALPOINT CLINICAL SERVICES', 55, 52);

  doc.fontSize(10)
     .font('Helvetica')
     .fillColor('#94A3B8')
     .text('Official Appointment Confirmation & Consultation Slip', 55, 75);

  doc.fontSize(8)
     .fillColor('#A7F3D0')
     .text(`Document Ref: #${apt.appointment_id}`, 380, 54, { align: 'right', width: 160 });
  doc.text(`Issued: ${new Date().toLocaleDateString()}`, 380, 68, { align: 'right', width: 160 });

  // 2. Appointment Identifier Banner
  let y = 125;
  doc.rect(40, y, 515, 36).fillAndStroke('#ECFDF5', '#A7F3D0');
  doc.fillColor(brandTeal)
     .fontSize(12)
     .font('Helvetica-Bold')
     .text(`APPOINTMENT #${apt.appointment_id} — ${apt.status || 'SCHEDULED'}`, 55, y + 11);

  doc.fillColor(textDark)
     .fontSize(9)
     .font('Helvetica-Bold')
     .text(`Type: ${apt.appointment_type === 'VIDEO' ? 'Telemedicine Video' : 'In-Person Consultation'}`, 340, y + 12, { align: 'right', width: 200 });

  // 3. Patient & Doctor Details Grid
  y = 175;
  doc.rect(40, y, 250, 110).fillAndStroke('#F8FAFC', borderLight);
  doc.rect(305, y, 250, 110).fillAndStroke('#F8FAFC', borderLight);

  // Patient Card
  doc.fillColor(brandTeal)
     .fontSize(9)
     .font('Helvetica-Bold')
     .text('PATIENT INFORMATION', 52, y + 10);

  doc.fillColor(textDark)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text(apt.patient_name || 'Demo Patient', 52, y + 26);

  doc.fillColor(textMuted)
     .fontSize(8.5)
     .font('Helvetica')
     .text(`Email: ${apt.patient_email || 'demo.patient@healpoint.com'}`, 52, y + 42)
     .text(`Patient ID: #${apt.patient_id || '1'}`, 52, y + 56)
     .text(`Account Verified: Active`, 52, y + 70);

  // Doctor Card
  doc.fillColor(brandTeal)
     .fontSize(9)
     .font('Helvetica-Bold')
     .text('PRACTITIONER INFORMATION', 317, y + 10);

  doc.fillColor(textDark)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text(apt.doctor_name || 'Dr. Priya Nair', 317, y + 26);

  doc.fillColor(brandTeal)
     .fontSize(8.5)
     .font('Helvetica-Bold')
     .text(`Specialty: ${apt.specialization || 'General Medicine'}`, 317, y + 42);

  doc.fillColor(textMuted)
     .fontSize(8.5)
     .font('Helvetica')
     .text(`Location: ${apt.location || 'HealPoint Health Clinic'}`, 317, y + 56)
     .text(`Doctor ID: #${apt.doctor_id || '101'}`, 317, y + 70);

  // 4. Schedule & Financials Section
  y = 300;
  doc.rect(40, y, 515, 120).fillAndStroke('#FFFFFF', borderLight);
  doc.fillColor(brandNavy)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text('CONSULTATION SCHEDULE & BILLING DETAILS', 55, y + 12);

  const formattedDate = apt.appointment_datetime 
    ? new Date(apt.appointment_datetime).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
    : 'Scheduled Date';
  const formattedTime = apt.appointment_datetime
    ? new Date(apt.appointment_datetime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    : '00:00';

  doc.fillColor(textDark)
     .fontSize(9)
     .font('Helvetica')
     .text(`Date & Time: `, 55, y + 34, { continued: true })
     .font('Helvetica-Bold').text(`${formattedDate} at ${formattedTime}`);

  doc.font('Helvetica')
     .text(`Consultation Mode: `, 55, y + 50, { continued: true })
     .font('Helvetica-Bold').text(`${apt.appointment_type === 'VIDEO' ? 'Encrypted Video Telemedicine' : 'In-Person Clinical Visit'}`);

  doc.font('Helvetica')
     .text(`Consultation Fee: `, 55, y + 66, { continued: true })
     .font('Helvetica-Bold').text(`$${apt.payment_amount || '65.00'}`);

  doc.font('Helvetica')
     .text(`Payment Status: `, 55, y + 82, { continued: true })
     .font('Helvetica-Bold').fillColor('#059669').text(`${apt.payment_status || 'PAID (COMPLETED)'}`);

  if (apt.telemedicine_url) {
    doc.fillColor(textMuted)
       .fontSize(8)
       .font('Helvetica')
       .text(`Telemedicine Room: ${apt.telemedicine_url}`, 55, y + 98);
  }

  // 5. Cancellation Reason (if applicable)
  if (apt.cancellation_reason) {
    y = 435;
    doc.rect(40, y, 515, 45).fillAndStroke('#FEF2F2', '#FECACA');
    doc.fillColor('#991B1B')
       .fontSize(9)
       .font('Helvetica-Bold')
       .text('ADMINISTRATIVE CANCELLATION RATIONALE', 55, y + 8);
    doc.fontSize(8.5)
       .font('Helvetica')
       .text(apt.cancellation_reason, 55, y + 24);
  }

  // 6. Security Seal & Signoff
  y = apt.cancellation_reason ? 495 : 440;
  doc.rect(40, y, 515, 60).fill('#F8FAFC');
  doc.fillColor(textMuted)
     .fontSize(8)
     .font('Helvetica')
     .text('Notice: This document is an administrative verification record generated by HealPoint Healthcare Systems. All medical data is processed in accordance with clinical privacy standards. For modifications or inquiries, contact administrator support.', 55, y + 12, { width: 485, lineGap: 2 });

  // Footer
  doc.fontSize(7.5)
     .fillColor(textMuted)
     .text('HealPoint Clinical Systems • Admin Governance Portal • End of Document', 40, 790, { align: 'center', width: 515 });

  return doc;
};

/**
 * Generate formatted SVG image buffer for bulk appointments report
 */
export const buildAppointmentsImageSvg = (appointments = [], filters = {}) => {
  const width = 1100;
  const rowHeight = 36;
  const height = Math.max(500, 240 + Math.min(appointments.length, 30) * rowHeight);

  const filterSummary = `Status: ${filters.status || 'ALL'} | Specialty: ${filters.specialty || 'ALL'} | Total Records: ${appointments.length}`;

  const rowsSvg = appointments.slice(0, 30).map((apt, idx) => {
    const y = 200 + idx * rowHeight;
    const bg = idx % 2 === 0 ? '#F8FAFC' : '#FFFFFF';
    const statusColor = apt.status === 'COMPLETED' ? '#059669' : (apt.status === 'CANCELLED' ? '#DC2626' : '#D97706');
    const dateStr = apt.appointment_datetime ? new Date(apt.appointment_datetime).toLocaleString() : 'N/A';

    return `
      <rect x="40" y="${y}" width="1020" height="${rowHeight}" fill="${bg}" stroke="#E2E8F0" stroke-width="1"/>
      <text x="55" y="${y + 22}" font-family="sans-serif" font-weight="bold" font-size="13" fill="#087F72">#${apt.appointment_id}</text>
      <text x="130" y="${y + 22}" font-family="sans-serif" font-weight="bold" font-size="13" fill="#172033">${escapeXml(apt.patient_name || 'Patient')}</text>
      <text x="340" y="${y + 22}" font-family="sans-serif" font-size="13" fill="#172033">${escapeXml(apt.doctor_name || 'Dr. Specialist')} (${escapeXml(apt.specialization || 'Medicine')})</text>
      <text x="640" y="${y + 22}" font-family="sans-serif" font-size="12" fill="#64748B">${dateStr}</text>
      <text x="820" y="${y + 22}" font-family="sans-serif" font-weight="bold" font-size="12" fill="${statusColor}">${apt.status}</text>
      <text x="960" y="${y + 22}" font-family="sans-serif" font-weight="bold" font-size="13" fill="#172033">$${apt.payment_amount || '65.00'}</text>
    `;
  }).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="${width}" height="${height}" fill="#F5F8F6"/>
  <!-- Header -->
  <rect x="40" y="30" width="1020" height="90" rx="8" fill="#111C2F"/>
  <rect x="40" y="120" width="1020" height="4" fill="#087F72"/>
  <text x="60" y="65" font-family="sans-serif" font-weight="bold" font-size="22" fill="#FFFFFF">HEALPOINT CLINICAL APPOINTMENTS REPORT</text>
  <text x="60" y="95" font-family="sans-serif" font-size="13" fill="#94A3B8">Report Generated on: ${new Date().toLocaleString()}</text>
  <text x="1030" y="65" text-anchor="end" font-family="sans-serif" font-size="12" fill="#A7F3D0">Confidential Healthcare Report</text>
  <text x="1030" y="95" text-anchor="end" font-family="sans-serif" font-weight="bold" font-size="13" fill="#A7F3D0">${filterSummary}</text>

  <!-- Table Header -->
  <rect x="40" y="155" width="1020" height="38" fill="#087F72"/>
  <text x="55" y="179" font-family="sans-serif" font-weight="bold" font-size="13" fill="#FFFFFF">ID</text>
  <text x="130" y="179" font-family="sans-serif" font-weight="bold" font-size="13" fill="#FFFFFF">PATIENT</text>
  <text x="340" y="179" font-family="sans-serif" font-weight="bold" font-size="13" fill="#FFFFFF">DOCTOR &amp; SPECIALTY</text>
  <text x="640" y="179" font-family="sans-serif" font-weight="bold" font-size="13" fill="#FFFFFF">SCHEDULED TIME</text>
  <text x="820" y="179" font-family="sans-serif" font-weight="bold" font-size="13" fill="#FFFFFF">STATUS</text>
  <text x="960" y="179" font-family="sans-serif" font-weight="bold" font-size="13" fill="#FFFFFF">FEE</text>

  <!-- Table Rows -->
  ${rowsSvg}
</svg>`;
};

/**
 * Generate formatted SVG image for a single appointment card
 */
export const buildSingleAppointmentImageSvg = (apt) => {
  const width = 800;
  const height = 520;
  const dateStr = apt.appointment_datetime ? new Date(apt.appointment_datetime).toLocaleString() : 'N/A';

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="${width}" height="${height}" fill="#F5F8F6"/>
  <!-- Card Shell -->
  <rect x="30" y="30" width="740" height="460" rx="14" fill="#FFFFFF" stroke="#E2E8F0" stroke-width="2"/>
  <!-- Card Header -->
  <rect x="30" y="30" width="740" height="85" rx="14" fill="#111C2F"/>
  <rect x="30" y="115" width="740" height="4" fill="#087F72"/>
  <text x="55" y="65" font-family="sans-serif" font-weight="bold" font-size="20" fill="#FFFFFF">HEALPOINT CLINICAL APPOINTMENT SUMMARY</text>
  <text x="55" y="92" font-family="sans-serif" font-size="12" fill="#94A3B8">Official Digital Consultation Verification Slip</text>
  <text x="740" y="65" text-anchor="end" font-family="sans-serif" font-weight="bold" font-size="14" fill="#A7F3D0">#${apt.appointment_id}</text>
  
  <!-- Content Details -->
  <rect x="55" y="140" width="325" height="130" rx="8" fill="#F8FAFC" stroke="#E2E8F0" stroke-width="1"/>
  <text x="70" y="165" font-family="sans-serif" font-weight="bold" font-size="12" fill="#087F72">PATIENT DETAILS</text>
  <text x="70" y="195" font-family="sans-serif" font-weight="bold" font-size="15" fill="#172033">${escapeXml(apt.patient_name || 'Patient')}</text>
  <text x="70" y="220" font-family="sans-serif" font-size="12" fill="#64748B">${escapeXml(apt.patient_email || 'demo.patient@healpoint.com')}</text>
  <text x="70" y="245" font-family="sans-serif" font-size="12" fill="#64748B">Patient ID: #${apt.patient_id || '1'}</text>

  <rect x="420" y="140" width="325" height="130" rx="8" fill="#F8FAFC" stroke="#E2E8F0" stroke-width="1"/>
  <text x="435" y="165" font-family="sans-serif" font-weight="bold" font-size="12" fill="#087F72">DOCTOR DETAILS</text>
  <text x="435" y="195" font-family="sans-serif" font-weight="bold" font-size="15" fill="#172033">${escapeXml(apt.doctor_name || 'Dr. Priya Nair')}</text>
  <text x="435" y="220" font-family="sans-serif" font-weight="bold" font-size="12" fill="#087F72">${escapeXml(apt.specialization || 'General Medicine')}</text>
  <text x="435" y="245" font-family="sans-serif" font-size="12" fill="#64748B">${escapeXml(apt.location || 'HealPoint Health Clinic')}</text>

  <!-- Summary Schedule -->
  <rect x="55" y="290" width="690" height="120" rx="8" fill="#F8FAFC" stroke="#E2E8F0" stroke-width="1"/>
  <text x="70" y="320" font-family="sans-serif" font-weight="bold" font-size="13" fill="#172033">CONSULTATION SCHEDULE &amp; BILLING</text>
  <text x="70" y="350" font-family="sans-serif" font-size="13" fill="#334155">Scheduled Time: <tspan font-weight="bold">${dateStr}</tspan></text>
  <text x="70" y="375" font-family="sans-serif" font-size="13" fill="#334155">Consultation Mode: <tspan font-weight="bold">${apt.appointment_type === 'VIDEO' ? 'Telemedicine Video' : 'In-Person Clinic'}</tspan></text>
  <text x="70" y="400" font-family="sans-serif" font-size="13" fill="#334155">Status: <tspan font-weight="bold" fill="${apt.status === 'COMPLETED' ? '#059669' : '#D97706'}">${apt.status}</tspan> | Fee: <tspan font-weight="bold">$${apt.payment_amount || '65.00'} (${apt.payment_status || 'PAID'})</tspan></text>

  <!-- Footer Notice -->
  <text x="400" y="460" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#94A3B8">HealPoint Healthcare Management System • Confidential Administration Document</text>
</svg>`;
};

function escapeXml(unsafe) {
  return String(unsafe || '').replace(/[<>&'"]/g, function (c) {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '\'': return '&apos;';
      case '"': return '&quot;';
    }
  });
}
