import PDFDocument from 'pdfkit';

/**
 * Generate a professional bulk appointments PDF report stream
 */
export const buildAppointmentsPdfStream = (appointments = [], filters = {}, adminUser = {}) => {
  const doc = new PDFDocument({
    margin: 40,
    size: 'A4',
    bufferPages: true,
    info: {
      Title: 'HealPoint Clinical Appointments Report',
      Author: 'HealPoint Healthcare Management System',
      Subject: 'Appointment Administration Report'
    }
  });

  // Colors
  const brandNavy = '#111C2F';
  const brandTeal = '#087F72';
  const textDark = '#172033';
  const textMuted = '#64748B';
  const borderLight = '#E2E8F0';
  const zebraBg = '#F8FAFC';

  // 1. Header Banner
  doc.rect(40, 40, 515, 60).fill(brandNavy);
  
  // Teal accent line
  doc.rect(40, 100, 515, 4).fill(brandTeal);

  doc.fillColor('#FFFFFF')
     .fontSize(16)
     .font('Helvetica-Bold')
     .text('HEALPOINT HEALTHCARE SYSTEMS', 55, 52);

  doc.fontSize(10)
     .font('Helvetica')
     .fillColor('#94A3B8')
     .text('Clinical Appointment Administration & Governance Report', 55, 74);

  doc.fontSize(8)
     .fillColor('#A7F3D0')
     .text(`Generated on: ${new Date().toLocaleString()}`, 380, 56, { align: 'right', width: 160 });

  doc.text(`Generated by: ${adminUser.email || 'admin@healpoint.com'}`, 380, 70, { align: 'right', width: 160 });

  // 2. Filter Summary Box
  let y = 120;
  doc.rect(40, y, 515, 45).fillAndStroke('#F1F5F9', borderLight);

  doc.fillColor(textDark)
     .fontSize(9)
     .font('Helvetica-Bold')
     .text('APPLIED REPORT FILTERS & PARAMETERS', 50, y + 8);

  const statusLabel = filters.status || 'ALL STATUSES';
  const specialtyLabel = filters.specialty || 'ALL SPECIALTIES';
  const searchLabel = filters.search ? `"${filters.search}"` : 'NONE';
  const dateRangeLabel = (filters.startDate || filters.endDate) 
    ? `${filters.startDate || 'Start'} to ${filters.endDate || 'Present'}`
    : 'ALL RECORDED DATES';

  doc.fontSize(8)
     .font('Helvetica')
     .fillColor(textMuted)
     .text(`Status Filter: `, 50, y + 24, { continued: true })
     .font('Helvetica-Bold').fillColor(textDark).text(`${statusLabel}   |   `, { continued: true })
     .font('Helvetica').fillColor(textMuted).text(`Specialty: `, { continued: true })
     .font('Helvetica-Bold').fillColor(textDark).text(`${specialtyLabel}   |   `, { continued: true })
     .font('Helvetica').fillColor(textMuted).text(`Date Range: `, { continued: true })
     .font('Helvetica-Bold').fillColor(textDark).text(`${dateRangeLabel}`);

  doc.font('Helvetica')
     .fillColor(textMuted)
     .text(`Search Term: `, 50, y + 34, { continued: true })
     .font('Helvetica-Bold').fillColor(textDark).text(`${searchLabel}   |   `, { continued: true })
     .font('Helvetica').fillColor(textMuted).text(`Matching Records: `, { continued: true })
     .font('Helvetica-Bold').fillColor(brandTeal).text(`${appointments.length} Bookings`);

  // 3. Table Header
  y = 180;
  const colX = { id: 45, patient: 85, doctor: 195, date: 310, type: 395, status: 455, fee: 510 };
  
  const drawTableHeader = (posY) => {
    doc.rect(40, posY, 515, 20).fill(brandTeal);
    doc.fillColor('#FFFFFF')
       .fontSize(8)
       .font('Helvetica-Bold')
       .text('ID', colX.id, posY + 6)
       .text('PATIENT', colX.patient, posY + 6)
       .text('DOCTOR & SPECIALTY', colX.doctor, posY + 6)
       .text('DATE & TIME', colX.date, posY + 6)
       .text('MODE', colX.type, posY + 6)
       .text('STATUS', colX.status, posY + 6)
       .text('FEE', colX.fee, posY + 6);
  };

  drawTableHeader(y);
  y += 20;

  // 4. Rows
  appointments.forEach((apt, idx) => {
    if (y > 740) {
      doc.addPage();
      y = 40;
      drawTableHeader(y);
      y += 20;
    }

    const isZebra = idx % 2 === 1;
    if (isZebra) {
      doc.rect(40, y, 515, 24).fill(zebraBg);
    }
    doc.rect(40, y, 515, 24).stroke(borderLight);

    const aptDate = new Date(apt.appointment_datetime);
    const dateStr = !isNaN(aptDate) ? aptDate.toLocaleDateString() : 'N/A';
    const timeStr = !isNaN(aptDate) ? aptDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '';

    doc.fillColor(textDark).fontSize(8).font('Helvetica-Bold').text(`#${apt.appointment_id}`, colX.id, y + 7);
    
    // Patient
    doc.font('Helvetica-Bold').text(apt.patient_name || 'Anonymous', colX.patient, y + 4, { width: 105, lineBreak: false, ellipsis: true });
    doc.font('Helvetica').fontSize(6.5).fillColor(textMuted).text(apt.patient_email || '', colX.patient, y + 14, { width: 105, lineBreak: false, ellipsis: true });

    // Doctor
    doc.fillColor(textDark).fontSize(8).font('Helvetica-Bold').text(apt.doctor_name || 'Assigned Doctor', colX.doctor, y + 4, { width: 110, lineBreak: false, ellipsis: true });
    doc.font('Helvetica').fontSize(6.5).fillColor(brandTeal).text(apt.specialization || 'General Practice', colX.doctor, y + 14, { width: 110, lineBreak: false, ellipsis: true });

    // Date & Time
    doc.fillColor(textDark).fontSize(7.5).font('Helvetica').text(`${dateStr} ${timeStr}`, colX.date, y + 7, { width: 80 });

    // Type
    doc.fontSize(7.5).text(apt.appointment_type === 'VIDEO' ? 'Telemedicine' : 'In-Person', colX.type, y + 7);

    // Status
    let statusColor = '#2563EB';
    if (apt.status === 'COMPLETED') statusColor = '#059669';
    if (apt.status === 'CANCELLED') statusColor = '#DC2626';
    doc.font('Helvetica-Bold').fillColor(statusColor).text(apt.status || 'SCHEDULED', colX.status, y + 7);

    // Fee
    doc.font('Helvetica-Bold').fillColor(textDark).text(`$${apt.payment_amount || '65.00'}`, colX.fee, y + 7);

    y += 24;
  });

  // Footer on all pages
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);
    doc.rect(40, 780, 515, 1).fill(borderLight);
    doc.fontSize(7.5)
       .font('Helvetica')
       .fillColor(textMuted)
       .text('HealPoint Healthcare Management System — Confidential Patient Telemetry Report', 40, 790);
    doc.text(`Page ${i + 1} of ${pages.count}`, 480, 790, { align: 'right', width: 75 });
  }

  return doc;
};

/**
 * Generate a single appointment verification / booking slip PDF stream
 */
export const buildSingleAppointmentPdfStream = (apt, adminUser = {}) => {
  const doc = new PDFDocument({
    margin: 40,
    size: 'A4',
    bufferPages: true,
    info: {
      Title: `HealPoint Appointment Slip #${apt.appointment_id}`,
      Author: 'HealPoint Healthcare Management System'
    }
  });

  const brandNavy = '#111C2F';
  const brandTeal = '#087F72';
  const textDark = '#172033';
  const textMuted = '#64748B';
  const borderLight = '#E2E8F0';

  // Card Frame
  doc.rect(40, 40, 515, 680).fillAndStroke('#FFFFFF', borderLight);

  // Top Header Banner
  doc.rect(40, 40, 515, 60).fill(brandNavy);
  doc.rect(40, 100, 515, 4).fill(brandTeal);

  doc.fillColor('#FFFFFF')
     .fontSize(16)
     .font('Helvetica-Bold')
     .text('HEALPOINT HEALTHCARE SYSTEMS', 55, 52);

  doc.fontSize(10)
     .font('Helvetica')
     .fillColor('#94A3B8')
     .text('Official Appointment Confirmation & Verification Slip', 55, 74);

  doc.fontSize(9)
     .fillColor('#A7F3D0')
     .text(`Slip ID: HP-${apt.appointment_id}`, 400, 60, { align: 'right', width: 140 });

  // Status Badge
  let y = 125;
  doc.rect(55, y, 485, 40).fillAndStroke('#F8FAFC', borderLight);
  doc.fillColor(textDark).fontSize(10).font('Helvetica-Bold').text(`APPOINTMENT REFERENCE: #${apt.appointment_id}`, 70, y + 14);
  
  let statusBadgeColor = '#059669';
  if (apt.status === 'CANCELLED') statusBadgeColor = '#DC2626';
  if (apt.status === 'SCHEDULED') statusBadgeColor = '#2563EB';

  doc.fillColor(statusBadgeColor).fontSize(10).font('Helvetica-Bold').text(`STATUS: ${apt.status}`, 420, y + 14, { align: 'right', width: 105 });

  // Details Grid
  y = 185;

  const drawField = (label, value, posX, posY, width = 230) => {
    doc.rect(posX, posY, width, 45).fillAndStroke('#FAFAFA', borderLight);
    doc.fillColor(textMuted).fontSize(8).font('Helvetica').text(label.toUpperCase(), posX + 10, posY + 8);
    doc.fillColor(textDark).fontSize(9.5).font('Helvetica-Bold').text(String(value || 'N/A'), posX + 10, posY + 22, { width: width - 20, lineBreak: false, ellipsis: true });
  };

  const aptDate = new Date(apt.appointment_datetime);
  const formattedDate = !isNaN(aptDate) ? aptDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : 'N/A';
  const formattedTime = !isNaN(aptDate) ? aptDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'N/A';

  drawField('Patient Full Name', apt.patient_name, 55, y);
  drawField('Patient Contact Email', apt.patient_email, 300, y);

  y += 55;
  drawField('Attending Doctor', apt.doctor_name, 55, y);
  drawField('Clinical Specialty', apt.specialization, 300, y);

  y += 55;
  drawField('Scheduled Date', formattedDate, 55, y);
  drawField('Scheduled Time Slot', formattedTime, 300, y);

  y += 55;
  drawField('Consultation Mode', apt.appointment_type === 'VIDEO' ? 'Telemedicine Video Consultation' : 'In-Person Hospital Visit', 55, y);
  drawField('Practice Location', apt.location || 'HealPoint Health Center', 300, y);

  y += 55;
  drawField('Consultation Fee', `$${apt.payment_amount || '65.00'}`, 55, y);
  drawField('Payment Status', apt.payment_status || 'PAID / COMPLETED', 300, y);

  if (apt.cancellation_reason) {
    y += 55;
    doc.rect(55, y, 475, 45).fillAndStroke('#FEF2F2', '#F87171');
    doc.fillColor('#B91C1C').fontSize(8).font('Helvetica-Bold').text('CANCELLATION RATIONALE / CLINICAL AUDIT NOTE', 65, y + 8);
    doc.fillColor('#991B1B').fontSize(8.5).font('Helvetica').text(apt.cancellation_reason, 65, y + 22, { width: 455 });
  }

  // Verification Box
  y = 500;
  doc.rect(55, y, 475, 120).fillAndStroke('#F1F5F9', borderLight);
  doc.fillColor(brandTeal).fontSize(9.5).font('Helvetica-Bold').text('ADMINISTRATIVE VERIFICATION & COMPLIANCE', 70, y + 14);
  doc.fillColor(textDark).fontSize(8).font('Helvetica')
     .text('This document certifies that the appointment recorded above is registered in the official HealPoint Clinical Management System database. For clinical rescheduling, emergency cancellations, or billing inquiries, please contact patient support.', 70, y + 32, { width: 445, lineGap: 3 });

  doc.fontSize(7.5).fillColor(textMuted).text(`Record Created: ${new Date(apt.created_at || Date.now()).toLocaleString()}  |  Admin Signed: ${adminUser.email || 'admin@healpoint.com'}`, 70, y + 95);

  // Footer
  doc.rect(40, 680, 515, 40).fill(brandNavy);
  doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica').text('HealPoint Healthcare Management System  •  Official Patient Verification Record', 55, 695);

  return doc;
};
